# Generated by Django 5.1.2 on 2025-04-16 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='current_match_index',
            field=models.IntegerField(default=0),
        ),
    ]
