# Generated by Django 5.1.2 on 2025-04-22 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='favorite_tradition',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='ghost_likelihood',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='goals_after',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='meet_people',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='personal_motto',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='personality_label',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='productivity_time',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='secret_campus_hack',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='todays_vibe',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='weekend_vibe',
        ),
        migrations.AlterField(
            model_name='profile',
            name='ideal_study_spot',
            field=models.CharField(choices=[('ajax', '🍳 Diner booth'), ('library', '📖 Library'), ('uptown', '☕ Coffee Shop'), ('couch', '🏡 At Home')], max_length=50),
        ),
    ]
