# Generated by Django 5.1.2 on 2025-03-26 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='disliked_profiles',
            field=models.ManyToManyField(blank=True, related_name='disliked_by', to='app.profile'),
        ),
        migrations.AddField(
            model_name='profile',
            name='liked_profiles',
            field=models.ManyToManyField(blank=True, related_name='liked_by', to='app.profile'),
        ),
    ]
