# Generated by Django 5.1.3 on 2025-04-15 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_profile_planner_fullness'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='campus_groups',
            field=models.CharField(choices=[('fraternity_sorority', '🏛 Fraternity/Sorority'), ('academic_clubs', '🧠 Academic clubs (e.g., Honors College, debate, CME)'), ('creative_orgs', '🎨 Creative orgs (e.g., theatre, film, writing)'), ('sports_intramurals', '🎽 Sports or intramurals'), ('music_arts_groups', '🎸 Music or arts-related groups'), ('class_match_5', 'Class Match 5'), ('religious_orgs', '🙏 Religious orgs (e.g., Cru, Young Life, RUF)'), ('service_groups', '🌍 Service & volunteer groups'), ('niche_clubs', '🧩 Niche interest clubs (e.g., gaming, outdoors, crypto, chess)'), ('not_involved', '🚫 Not involved (yet!)')], max_length=50),
        ),
    ]
