# Generated by Django 5.1.2 on 2025-03-27 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_profile_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='age',
            field=models.IntegerField(default=18),
        ),
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='profile',
            name='classes',
            field=models.ManyToManyField(to='app.class'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='study_times',
            field=models.CharField(max_length=255),
        ),
    ]
