# Generated by Django 5.1.2 on 2025-04-02 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_friendrequest_unique_together'),
        ('app', '0009_remove_profile_bio_remove_profile_classes_and_more'),
    ]

    operations = [
    ]
