# Generated by Django 5.1.2 on 2025-04-03 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_event'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='description',
        ),
        migrations.AddField(
            model_name='event',
            name='days',
            field=models.CharField(default='Unknown', max_length=100),
        ),
    ]
