# Generated by Django 5.1.2 on 2025-04-07 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_friendrequest_declined'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='pending_sent_requests',
            field=models.ManyToManyField(blank=True, related_name='pending_received_requests', to='app.profile'),
        ),
    ]
